nome = str(input('Digitr seu nome completo ?')).strip()
print('Analisando seu nome')
print('Seu nome em maiuscula é {}'.format(nome.upper()))
print('Seu nome em minuscula é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
#print('seu priemiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print(separa)
#print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0]))
